# Generated by Django 5.1.7 on 2025-04-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
