# Generated by Django 5.1.7 on 2025-04-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album_app', '0001_initial'),
        ('artist_app', '__first__'),
        ('genre_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default="This song hasn't been given a description yet.", max_length=255, null=True)),
                ('albums', models.ManyToManyField(related_name='songs', to='album_app.album')),
                ('artist', models.ManyToManyField(related_name='songs', to='artist_app.artist')),
                ('genres', models.ManyToManyField(related_name='songs', to='genre_app.genre')),
            ],
        ),
    ]
