# Generated by Django 5.1.7 on 2025-04-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0002_album_artist_album_genres'),
        ('artist_app', '0003_artist_description'),
        ('genre_app', '0001_initial'),
        ('song_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='albums',
            field=models.ManyToManyField(related_name='songs', to='album_app.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(related_name='songs', to='artist_app.artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(related_name='songs', to='genre_app.genre'),
        ),
    ]
