# Generated by Django 5.1.7 on 2025-04-02 02:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('song_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('songs', models.ManyToManyField(related_name='playlists', to='song_app.song')),
                ('user_id', models.ManyToManyField(related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
