# Generated by Django 5.1.7 on 2025-04-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0003_playlist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
