from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator
from django.db import models

# Create your models here.
class Album(models.Model):
  # TO DO : create field for album_img
  name = models.CharField(max_length=100, null=False, blank=True)
  description = models.CharField(max_length=255, null=True, default="This album hasn't been given a description yet.")
  # genre field generated by Genre model as "genres" MtM
  # songs field generated by songs model as "songs" MtM
  # artist field generated by Artist model as "artists" MtM
