# Generated by Django 5.1.7 on 2025-04-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0002_album_artist_album_genres'),
        ('genre_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(related_name='albums', to='genre_app.genre'),
        ),
    ]
