from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.models import AbstractUser
from django.db import models
from genre_app.serializers import Genre

# Create your models here.
class Artist(models.Model):
  # TO DO : create artist_img field 
  name = models.CharField(max_length=100, null=False, blank=False)
  description = models.CharField(max_length=255, null=True, default="This artist hasn't been given a description yet.")
  genres = models.ManyToManyField(Genre, related_name="artists") # creating association between Artist-Genre
  # albums field generated by Album model as "albums" MtM
  # songs field generated by Songs model as "songs" MtM