# Generated by Django 5.1.7 on 2025-04-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='album_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='album_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='artist_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='artist_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='track_img_lg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='track_img_md',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='track_img_sm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
