# Generated by Django 5.1.7 on 2025-04-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default="This artist hasn't been given a description yet.", max_length=255, null=True)),
                ('genres', models.ManyToManyField(related_name='artists', to='genre_app.genre')),
            ],
        ),
    ]
