# Generated by Django 5.1.7 on 2025-04-02 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artists',
            new_name='Artist',
        ),
    ]
