# Generated by Django 5.1.7 on 2025-04-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0002_rename_artists_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.CharField(default="This artist hasn't been given a description yet.", max_length=255, null=True),
        ),
    ]
