# Generated by Django 5.1.7 on 2025-04-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0003_artist_description'),
        ('genre_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(related_name='artists', to='genre_app.genre'),
        ),
    ]
